apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-hello-application
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: install/argocd/php-hello/
    repoURL: 'https://github.com/djkormo/AKS-security.git'
    targetRevision: HEAD
  project: default